#!/bin/bash
LeHelp()
{
	echo "QLS: Quick List"
	echo "Copyright (c) 2024 Jacob 'Yeetsup' Hache"
	echo "Available Flags:"
	echo "	-b	Lists your BIN/ directory"
	echo "	-h	Lists your HOME/ directory"
	echo "	-H	Displays this help and stops"
}
if (( $# == 0 )); then
LeHelp
echo -e "\x1b[1;31m[1]: qls needs a flag to run\x1b[0m"
exit 1
fi
while getopts bHh flag
do
case "${flag}" in
b) 
echo "Files and Folders in BIN/(${PATH}):"
ls $PATH
;;
h) 
echo "Files and folders in home/(${HOME}):"
ls $HOME
;;
H)
LeHelp
exit
;;
esac
done
