#!/bin/sh

clear
echo "Welcome to yeet's scripts installer v1.3-alpha! This installer will download scripts to $PATH so they can be executed by name (that way you don't have to write the path every time)."
sleep 2s
echo "Starting download..."
echo "Downloading Yeet's Memes v1.4-alpha(executable as 'yeetsmemes') to $PATH..."
curl -s -o $PATH/yeetsmemes "https://yeetssite.github.io/scripts/yeetsmemes"
chmod u+r+x $PATH/yeetsmemes
echo "Finished!"
echo "Starting download..."
echo "Downloading Quick List v1.2-alpha(executable as 'qls -[OPTION]') to $PATH..."
curl -s -o $PATH/qls "https://yeetssite.github.io/scripts/qls"
chmod u+r+x $PATH/qls
echo "Finished!"
echo "Download Finished!"
