#!/bin/bash
LeHelp()
{
	echo "QLS | Quick List"
	echo "Copyright (c) 2024 Jacob 'Yeetsup' Hache."
	echo "Available Flags:"
	echo "	-b   --bin	Lists your BIN/ directory."
	echo "	-h   --home	Lists your HOME/ directory."
	echo "	-H   --help	Displays this help and exits."
	echo "	-v   --version	Displays the installed version."
}
LeVersion()
{
	echo -e "\x1b[1;34mQLS v1.3-alpha\x1b[0m"
	echo "Copyright (c) 2024 Jacob 'Yeetsup' Hache."
	echo -e "Use \x1b[35m'qls -H'\x1b[0m for help."
	
}
if [ -z $1 ]; then
LeHelp
echo -e "\x1b[1;31m[1]: qls needs a flag to run\x1b[0m"
exit 1
fi
case "$1" in
-b | --bin) 
echo "Files and Folders in BIN/(${PATH}):"
ls $PATH
;;
-h | --home) 
echo "Files and folders in home/(${HOME}):"
ls $HOME
;;
-H | --help)
LeHelp
exit
;;
-v | --version)
LeVersion
exit
;;
? | *)
LeHelp
echo -e "\x1b[1;31m[2]: \"$1\" isn't an option."
;;
esac

